Hw2
Gokert/Homework_Go pull request #3
Opened 2023-11-06 12:57 UTC by Gokert

2023-11-06 16:36 UTC, migregal commented on spammer.go
> +				GetUser("")
Чутка стили поехали

2023-11-06 16:38 UTC, migregal requested changes
Микрозамечание, в остальном вроде ок

2023-11-07 06:09 UTC, migregal commented on spammer.go
> +				GetUser("")
А вот это зачем нужно?

Только сейчас заметил

2023-11-07 06:10 UTC, migregal commented on spammer.go
> +			}
Обычно, в гощке используют проверку наличия в map

```suggestion
			alias, found := usersAliases[emailStr]

			if found {
				emailStr = alias
			}
```

2023-11-07 07:24 UTC, Gokert commented on spammer.go
> +				GetUser("")
SelectUsers должен возвращать уникальных юзеров, то есть для 5го теста из 10 почт мы должны вернуть 9 уникальных юзеров, однако функцию GetUser мы должны вызвать 10 раз, а не 9 , хотя зачем ? Если уникальных юзеров 9, зачем вызывать 10 раз GetUser ? Просто не нужно, однако если это убрать , то тесты упадут

2023-11-07 07:25 UTC, Gokert commented on spammer.go
> +				GetUser("")
Я как раз тебе в личку с этим писал

2023-11-07 08:28 UTC, migregal approved these changes
lgtm

2023-11-16 21:12 UTC, merged